# Generated by Django 6.0.5 on 2026-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='quantity_kg',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('WHOLESALER', 'wholesaler'), ('RETAILER', 'retailer')], default='RETAILER', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
